name: Release
on:
    push:
        branches:
            - main
            - v2
            - v3
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
          - name: Release
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: npx semantic-release
